# Repaso: Lectura de datos con Pandas

## Preparación para certificación – Análisis de Datos

En esta sección trabajaremos principalmente con la **lectura de archivos CSV y Excel** utilizando `pandas`.

Usaremos el archivo de ventas mensuales proporcionado para resolver preguntas de:

- **Código**
- **Selección múltiple**
- **Interpretación de resultados**
- **Diagnóstico de errores frecuentes**

El archivo contiene información sobre:

- `fecha`
- `sucursal`
- `vendedor`
- `producto`
- `categoria`
- `cantidad`
- `precio`

> **Objetivo:** al finalizar deberías ser capaz de cargar un archivo, identificar su estructura básica y reconocer problemas comunes durante la lectura de datos.

# 1. Importar Pandas

Antes de leer un archivo tabular necesitamos importar la biblioteca.

## Pregunta 1 – Selección múltiple

¿Cuál es la forma más utilizada para importar Pandas?

A)
```python
import pandas
```

B)
```python
import pandas as pd
```

C)
```python
from pandas import *
```

D)
```python
import pd
```

In [ ]:
import pandas as pd

# Respuesta correcta: B

# 2. Lectura de un archivo CSV

El archivo proporcionado se llama:

```text
01. Apoyo ejercicio - Ventas mensuales.csv
```

## Problema 1: Cargar las ventas

Completa el código para cargar el archivo en un DataFrame llamado `df`.

### Pregunta

¿Cuál alternativa es correcta?

A)
```python
df = pd.read_excel("01. Apoyo ejercicio - Ventas mensuales.csv")
```

B)
```python
df = pd.read_csv("01. Apoyo ejercicio - Ventas mensuales.csv")
```

C)
```python
df = pd.open_csv("01. Apoyo ejercicio - Ventas mensuales.csv")
```

D)
```python
df = pd.load_csv("01. Apoyo ejercicio - Ventas mensuales.csv")
```

In [ ]:
# Ajusta la ruta si el archivo se encuentra en otra carpeta
archivo = "01. Apoyo ejercicio - Ventas mensuales.csv"

df = pd.read_csv("01. Apoyo ejercicio - Ventas mensuales.csv")

df.head(6)

# Respuesta correcta: B

,fecha,sucursal,vendedor,producto,categoria,cantidad,precio
0,2024-05-01,Santiago Centro,Carlos Soto,Pan Molde 550g,Panadería,9,862.0
1,2024-05-01,Santiago Centro,Carlos Soto,Aceite Vegetal 1L,Abarrotes,5,2076.0
2,2024-05-01,Santiago Centro,Carlos Soto,Atún en Lata 170g,Conservas,18,1452.0
3,2024-05-02,Santiago Centro,Carlos Soto,Jabón Barra x3,Limpieza,2,1757.0
4,2024-05-02,Santiago Centro,Carlos Soto,Leche Entera 1L,Lácteos,7,959.0
5,2024-05-02,Santiago Centro,Carlos Soto,Jugo Natural 1L,Bebidas,20,1606.0

# 3. ¿Qué es un DataFrame?

Después de ejecutar:

```python
df = pd.read_csv("01. Apoyo ejercicio - Ventas mensuales.csv")
```

la variable `df` contiene una estructura tabular llamada **DataFrame**.

## Pregunta 2 – Selección múltiple

¿Cuál afirmación describe mejor un DataFrame?

A) Una única variable numérica.  
B) Una estructura tabular formada por filas y columnas.  
C) Una función para leer archivos.  
D) Una lista que solo contiene texto.

In [ ]:
print(type(df))

# Respuesta correcta: B

<class 'pandas.core.frame.DataFrame'>

# 4. Visualizar las primeras filas

Una vez cargados los datos, normalmente queremos verificar que la lectura fue correcta.

## Problema 2

¿Qué método permite visualizar por defecto las primeras 5 filas?

A) `df.info()`  
B) `df.head()`  
C) `df.describe()`  
D) `df.columns()`

In [ ]:
df.head()

# Respuesta correcta: B

# También podemos indicar la cantidad de filas:
df.head(3)

,fecha,sucursal,vendedor,producto,categoria,cantidad,precio
0,2024-05-01,Santiago Centro,Carlos Soto,Pan Molde 550g,Panadería,9,862.0
1,2024-05-01,Santiago Centro,Carlos Soto,Aceite Vegetal 1L,Abarrotes,5,2076.0
2,2024-05-01,Santiago Centro,Carlos Soto,Atún en Lata 170g,Conservas,18,1452.0

## Problema 3: Interpretación

Observa las primeras filas del archivo.

### Pregunta

¿Cuál de las siguientes variables representa el nombre del producto vendido?

A) `vendedor`  
B) `categoria`  
C) `producto`  
D) `cantidad`

> Revisa los datos antes de responder.

In [ ]:
df.head()

# Respuesta: C

,fecha,sucursal,vendedor,producto,categoria,cantidad,precio
0,2024-05-01,Santiago Centro,Carlos Soto,Pan Molde 550g,Panadería,9,862.0
1,2024-05-01,Santiago Centro,Carlos Soto,Aceite Vegetal 1L,Abarrotes,5,2076.0
2,2024-05-01,Santiago Centro,Carlos Soto,Atún en Lata 170g,Conservas,18,1452.0
3,2024-05-02,Santiago Centro,Carlos Soto,Jabón Barra x3,Limpieza,2,1757.0
4,2024-05-02,Santiago Centro,Carlos Soto,Leche Entera 1L,Lácteos,7,959.0

# 5. Visualizar las últimas filas

## Pregunta 3

¿Qué método permite observar las últimas filas de un DataFrame?

A) `df.tail()`  
B) `df.end()`  
C) `df.last()`  
D) `df.bottom()`

In [ ]:
df.tail(3)

# Respuesta correcta: A

# También:
df.tail(3)

,fecha,sucursal,vendedor,producto,categoria,cantidad,precio
1193,2024-05-30,Rancagua,Felipe Herrera,Yogurt Natural 500g,Lácteos,18,1241.0
1194,2024-05-30,Rancagua,Felipe Herrera,Aceite Vegetal 1L,Abarrotes,19,2094.0
1195,2024-05-30,Rancagua,Felipe Herrera,Jabón Barra x3,Limpieza,10,1825.0

# 6. Conocer la estructura de los datos

## Problema 4: ¿Cuántas filas y columnas tiene el archivo?

Una analista necesita conocer rápidamente la dimensión del conjunto de datos.

¿Qué atributo utilizaría?

A) `df.size`  
B) `df.shape`  
C) `df.info()`  
D) `df.columns`

In [ ]:
print(df.shape)

filas, columnas = df.shape

print("Cantidad de filas:", filas)
print("Cantidad de columnas:", columnas)

# Respuesta correcta: B

(1196, 7)
Cantidad de filas: 1196
Cantidad de columnas: 7

In [ ]:
df.shape

(1196, 7)

# 7. Nombres de columnas

## Problema 5

Queremos conocer exactamente los nombres de las variables disponibles.

¿Qué atributo debemos utilizar?

A) `df.variables`  
B) `df.names`  
C) `df.columns`  
D) `df.head()`

In [ ]:
print(df.columns)

# También es posible convertirlo en lista:
print(df.columns.tolist())

# Respuesta correcta: C

Index(['fecha', 'sucursal', 'vendedor', 'producto', 'categoria', 'cantidad',
       'precio'],
      dtype='object')
['fecha', 'sucursal', 'vendedor', 'producto', 'categoria', 'cantidad', 'precio']

# 8. Información general del DataFrame

El método `info()` es especialmente útil para revisar:

- número de filas;
- nombres de columnas;
- cantidad de valores no nulos;
- tipo de dato de cada variable.

## Pregunta 4 – Selección múltiple

¿Qué método utilizarías para obtener esta información?

A) `df.info()`  
B) `df.head()`  
C) `df.sum()`  
D) `df.shape()`

In [ ]:
df.info()

# Respuesta correcta: A

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha      1196 non-null   object
 1   sucursal   1196 non-null   object
 2   vendedor   1196 non-null   object
 3   producto   1196 non-null   object
 4   categoria  1196 non-null   object
 5   cantidad   1196 non-null   object
 6   precio     1195 non-null   float64
dtypes: float64(1), object(6)
memory usage: 65.5+ KB

## Problema 6: Detectar una posible inconsistencia

Revisa la salida de:

```python
df.info()
```

### Pregunta

¿Todas las columnas tienen necesariamente el tipo de dato que esperaríamos a partir de su significado?

Por ejemplo, analiza especialmente:

- `fecha`
- `cantidad`
- `precio`

**Discusión:** un valor inesperado o un formato incorrecto puede provocar que Pandas interprete una columna de forma distinta a la esperada.

In [ ]:
df.info()

# Exploramos los valores de cantidad
print(df["cantidad"].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha      1196 non-null   object
 1   sucursal   1196 non-null   object
 2   vendedor   1196 non-null   object
 3   producto   1196 non-null   object
 4   categoria  1196 non-null   object
 5   cantidad   1196 non-null   object
 6   precio     1195 non-null   float64
dtypes: float64(1), object(6)
memory usage: 65.5+ KB
['9' '5' '18' '2' '7' '20' '8' '14' '3' '12' '15' '6' 'diez' '11' '19'
 '16' '4' '1' '17' '10' '13']

# 9. Problema real: una columna numérica leída como texto

En el archivo existe al menos un valor de `cantidad` que no corresponde a un número escrito únicamente con dígitos.

Esto puede provocar que Pandas interprete toda la columna como `object`.

## Pregunta 5

Si una columna contiene:

```text
5
10
18
diez
7
```

¿Cuál es el problema más probable?

A) Pandas convertirá automáticamente `"diez"` en `10`.  
B) La presencia de texto puede impedir que toda la columna sea interpretada como numérica.  
C) Pandas eliminará automáticamente la fila.  
D) La columna se convertirá en `bool`.

In [ ]:
# Identificamos los valores que no son numéricos
cantidad_numerica = pd.to_numeric(df["cantidad"], errors="coerce")

problemas = df[cantidad_numerica.isna()]

problemas

### Discusión

La instrucción:

```python
pd.to_numeric(..., errors="coerce")
```

intenta convertir los valores a números.

Cuando encuentra un valor que no puede convertir, lo reemplaza por `NaN`.

> En una evaluación podrían preguntar qué ocurre con un valor no convertible cuando se utiliza `errors="coerce"`.

**Respuesta:** se convierte en `NaN`.

In [ ]:
df["cantidad"] = df["cantidad"].replace("diez", 10)

In [ ]:
cantidad_numerica = pd.to_numeric(df["cantidad"], errors="coerce")

problemas = df[cantidad_numerica.isna()]

problemas

Empty DataFrame
Columns: [fecha, sucursal, vendedor, producto, categoria, cantidad, precio]
Index: []

In [ ]:
df[["precio","cantidad"]]

      precio  cantidad
0      862.0         9
1     2076.0         5
2     1452.0        18
3     1757.0         2
4      959.0         7
...      ...       ...
1191  1261.0         6
1192  1511.0        16
1193  1241.0        18
1194  2094.0        19
1195  1825.0        10

[1196 rows x 2 columns]

In [ ]:
df["cantidad"] = pd.to_numeric(df["cantidad"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha      1196 non-null   object
 1   sucursal   1196 non-null   object
 2   vendedor   1196 non-null   object
 3   producto   1196 non-null   object
 4   categoria  1196 non-null   object
 5   cantidad   1196 non-null   int64
 6   precio     1195 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 65.5+ KB

# 10. Leer fechas correctamente

La columna `fecha` contiene valores como:

```text
2024-05-01
2024-05-02
```

Al leer un CSV, Pandas puede cargar esta variable inicialmente como texto.

## Problema 7

¿Qué opción permite indicar, durante la lectura, que la columna `fecha` debe interpretarse como fecha?

A)
```python
pd.read_csv(archivo, date="fecha")
```

B)
```python
pd.read_csv(archivo, parse_dates=["fecha"])
```

C)
```python
pd.read_csv(archivo, datetime="fecha")
```

D)
```python
pd.read_csv(archivo, convert_date=True)
```

In [ ]:
archivo = "01. Apoyo ejercicio - Ventas mensuales.csv"

df_fechas = pd.read_csv(
    archivo,
    parse_dates=["fecha"]
)

df_fechas.info()

# Respuesta correcta: B

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1196 entries, 0 to 1195
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   fecha      1196 non-null   object
 1   sucursal   1196 non-null   object
 2   vendedor   1196 non-null   object
 3   producto   1196 non-null   object
 4   categoria  1196 non-null   object
 5   cantidad   1196 non-null   object
 6   precio     1195 non-null   float64
dtypes: float64(1), object(6)
memory usage: 65.5+ KB

# 11. Lectura de archivos Excel

Para leer un archivo Excel se utiliza:

```python
pd.read_excel()
```

Supongamos que el mismo conjunto de datos se encuentra en:

```text
01. Apoyo ejercicio - Ventas mensuales.xlsx
```

## Pregunta 6

¿Cuál es la instrucción correcta?

A)
```python
df_excel = pd.read_csv("ventas.xlsx")
```

B)
```python
df_excel = pd.read_excel("ventas.xlsx")
```

C)
```python
df_excel = pd.open_excel("ventas.xlsx")
```

D)
```python
df_excel = pd.load_excel("ventas.xlsx")
```

In [ ]:
archivo_excel = "01. Apoyo ejercicio - Ventas mensuales.xlsx"

df_excel = pd.read_excel(archivo_excel)

df_excel.head()

# Respuesta correcta: B

FileNotFoundError: [Errno 2] No such file or directory: '01. Apoyo ejercicio - Ventas mensuales.xlsx'

# 12. Hojas de un archivo Excel

Un archivo Excel puede contener varias hojas.

Supongamos que existe una hoja llamada:

```text
Ventas
```

## Problema 8

¿Cómo indicarías la hoja que deseas leer?

A)
```python
pd.read_excel("ventas.xlsx", hoja="Ventas")
```

B)
```python
pd.read_excel("ventas.xlsx", sheet_name="Ventas")
```

C)
```python
pd.read_excel("ventas.xlsx", page="Ventas")
```

D)
```python
pd.read_excel("ventas.xlsx", worksheet="Ventas")
```

In [ ]:
# Ejemplo general:
# df_ventas = pd.read_excel("ventas.xlsx", sheet_name="Ventas")

# También se puede usar la posición de la hoja:
# df_ventas = pd.read_excel("ventas.xlsx", sheet_name=0)

# Respuesta correcta: B

# 13. Diferencias frecuentes entre CSV y Excel

## Pregunta 7 – Selección múltiple

Relaciona cada función con el formato adecuado:

| Función | Formato |
|---|---|
| `pd.read_csv()` | ? |
| `pd.read_excel()` | ? |

Opciones:

A) Ambas leen únicamente archivos CSV.  
B) `read_csv()` se utiliza para CSV y `read_excel()` para Excel.  
C) `read_csv()` se utiliza para Excel y `read_excel()` para CSV.  
D) Ambas funcionan únicamente con archivos `.xlsx`.

# 14. Separadores en archivos CSV

No todos los CSV utilizan una coma como separador.

Por ejemplo, algunos archivos utilizan:

```text
fecha;sucursal;vendedor
```

## Problema 9

¿Qué argumento permite indicar que el separador es `;`?

A)
```python
pd.read_csv("archivo.csv", separator=";")
```

B)
```python
pd.read_csv("archivo.csv", sep=";")
```

C)
```python
pd.read_csv("archivo.csv", delimiter_excel=";")
```

D)
```python
pd.read_csv("archivo.csv", comma=";")
```

In [ ]:
# Ejemplo general:
# df = pd.read_csv("archivo.csv", sep=";")

# Respuesta correcta: B

# 15. Selección de una columna después de leer los datos

Una vez cargado el archivo, queremos trabajar solamente con la columna `precio`.

## Pregunta 8

¿Cuál es una forma correcta?

A)
```python
df("precio")
```

B)
```python
df["precio"]
```

C)
```python
df.precio()
```

D)
```python
df.get_column("precio")
```

In [ ]:
precio = df["precio"]

print(precio.head())

# Respuesta correcta: B

# 16. Seleccionar varias columnas

## Problema 10

Una analista necesita crear una vista con:

- `fecha`
- `sucursal`
- `precio`

¿Cuál código es correcto?

A)
```python
df["fecha", "sucursal", "precio"]
```

B)
```python
df[["fecha", "sucursal", "precio"]]
```

C)
```python
df("fecha", "sucursal", "precio")
```

D)
```python
df.select("fecha", "sucursal", "precio")
```

In [ ]:
columnas = df[["fecha", "sucursal", "precio"]]

columnas.head()

# Respuesta correcta: B

# 17. Desafío de código: lectura y diagnóstico inicial

## Situación

Eres analista de datos de una cadena de supermercados. Te entregan un archivo con ventas mensuales.

Tu tarea inicial es:

1. Importar Pandas.
2. Leer el archivo CSV.
3. Mostrar las primeras 10 filas.
4. Determinar el número de filas y columnas.
5. Mostrar los nombres de las columnas.
6. Obtener información general con `info()`.
7. Identificar si existe algún posible problema en los tipos de datos.

### Intenta resolverlo antes de ejecutar la solución.

In [ ]:
import pandas as pd

archivo = "01. Apoyo ejercicio - Ventas mensuales.csv"

# 1. Lectura
df = pd.read_csv(archivo)

# 2. Primeras filas
print("PRIMERAS 10 FILAS")
display(df.head(10))

# 3. Dimensión
filas, columnas = df.shape
print(f"Filas: {filas}")
print(f"Columnas: {columnas}")

# 4. Nombres
print("\nCOLUMNAS")
print(df.columns.tolist())

# 5. Información general
print("\nINFORMACIÓN")
df.info()

# 18. Desafío: lectura mejorada

Ahora queremos cargar el archivo considerando que:

- `fecha` debe ser interpretada como fecha.
- `cantidad` debería ser numérica.
- Si existe un valor no convertible, queremos detectarlo.

### Actividad

Completa el siguiente flujo:

1. Lee el archivo utilizando `parse_dates`.
2. Convierte `cantidad` a numérico.
3. Utiliza `errors="coerce"`.
4. Identifica las filas que generaron valores faltantes durante la conversión.

In [ ]:
archivo = "01. Apoyo ejercicio - Ventas mensuales.csv"

# Lectura de fecha
df = pd.read_csv(
    archivo,
    parse_dates=["fecha"]
)

# Conversión de cantidad
df["cantidad_numerica"] = pd.to_numeric(
    df["cantidad"],
    errors="coerce"
)

# Filas con problemas de conversión
errores_conversion = df[df["cantidad_numerica"].isna()]

display(errores_conversion)

# Revisar estructura
df.info()

# 19. Mini simulación – Selección múltiple

## Pregunta 1

¿Qué función se utiliza principalmente para leer un archivo CSV?

A) `pd.read_table()`  
B) `pd.read_csv()`  
C) `pd.read_excel()`  
D) `pd.load_csv()`

---

## Pregunta 2

¿Qué función permite leer un archivo Excel?

A) `pd.read_excel()`  
B) `pd.read_csv()`  
C) `pd.open_excel()`  
D) `pd.load_excel()`

---

## Pregunta 3

¿Qué método permite visualizar las primeras 5 filas?

A) `df.info()`  
B) `df.head()`  
C) `df.tail()`  
D) `df.shape`

---

## Pregunta 4

¿Qué atributo devuelve una tupla con el número de filas y columnas?

A) `df.columns`  
B) `df.size()`  
C) `df.shape`  
D) `df.info()`

---

## Pregunta 5

¿Qué método permite revisar tipos de datos y valores no nulos?

A) `df.info()`  
B) `df.head()`  
C) `df.columns()`  
D) `df.type()`

---

## Pregunta 6

¿Qué argumento permite leer una columna como fecha?

A) `date_columns`  
B) `parse_dates`  
C) `datetime_columns`  
D) `format_dates`

---

## Pregunta 7

Si un archivo CSV utiliza `;` como separador, ¿qué argumento puede utilizarse?

A) `sep=";"`  
B) `comma=";"`  
C) `split=";"`  
D) `csv_sep=";"`

---

## Pregunta 8

¿Qué ocurre al utilizar:

```python
pd.to_numeric(serie, errors="coerce")
```

sobre un valor no convertible?

A) Python detiene automáticamente el programa.  
B) El valor se elimina.  
C) El valor se convierte en `NaN`.  
D) El valor se convierte automáticamente en `0`.

---

## Pregunta 9

¿Cuál es la sintaxis correcta para seleccionar dos columnas?

A)
```python
df["fecha", "precio"]
```

B)
```python
df[["fecha", "precio"]]
```

C)
```python
df("fecha", "precio")
```

D)
```python
df.columns("fecha", "precio")
```

---

## Pregunta 10

¿Cuál es la principal estructura creada por Pandas al leer un archivo tabular?

A) `DataFrame`  
B) `Dictionary`  
C) `Tuple`  
D) `Function`

# Respuestas de la mini simulación

| Pregunta | Respuesta |
|---|---|
| 1 | B |
| 2 | A |
| 3 | B |
| 4 | C |
| 5 | A |
| 6 | B |
| 7 | A |
| 8 | C |
| 9 | B |
| 10 | A |

---

# Checklist final

Antes de continuar con el siguiente módulo deberías poder:

- [ ] Importar Pandas con `import pandas as pd`.
- [ ] Leer un archivo CSV con `pd.read_csv()`.
- [ ] Leer un archivo Excel con `pd.read_excel()`.
- [ ] Indicar una hoja con `sheet_name`.
- [ ] Modificar el separador de un CSV con `sep`.
- [ ] Visualizar datos con `head()` y `tail()`.
- [ ] Conocer las dimensiones con `shape`.
- [ ] Identificar los nombres de columnas con `columns`.
- [ ] Revisar tipos y valores no nulos con `info()`.
- [ ] Leer fechas con `parse_dates`.
- [ ] Detectar problemas de conversión con `pd.to_numeric(..., errors="coerce")`.
- [ ] Seleccionar una o varias columnas de un DataFrame.